--- 

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "copy backend binaries"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "copy node_modules"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
      
  - name: "start server"
    become: true
    command: pm2 stop default

  - name: "start server"
    become: true
    command: pm2 start npm -- start
